# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release MinimalMediator

on:
  push:
    branches: [ "main" ]

env:
  FEED_URL: https://api.nuget.org/v3/index.json
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '8.x'             # set this to the .NET version to use; 5.x, 6.x, or 7.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - run: echo "NBGV_SemVer1 $NBGV_SemVer2"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  feed-build-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup versioning
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and package
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}' /p:PublicRelease=true /p:Version=$NBGV_NuGetPackageVersion
          dotnet pack -c '${{ env.BUILD_CONFIGURATION }}' -o ./artifacts /p:PublicRelease=true /p:Version=$NBGV_NuGetPackageVersion
      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push ./artifacts/**.nupkg --source ${{ env.FEED_URL }} --api-key ${{ secrets.FEED_PAT }}
